import imgApi from '~/public/images/imgAPI';

const testimonialsData = [
  {
    avatar: imgApi.avatar[0],
    name: 'Lance Jarvis',
    title: 'General Manager',
    text: 'We have been using product for last one year, and I have to say that it has transformed the way we do business. Thank you for awesome service.',
    x: 100,
    y: 150,
  },
  {
    avatar: imgApi.avatar[1],
    name: 'Juliet Wright',
    title: 'Technical Director',
    text: 'It has changed the way I used the website. Product lets you create anything you envision and it does it so easy and flawless. I can`t imagine not working with the service.',
    x: 120,
    y: 100,
  },
  {
    avatar: imgApi.avatar[2],
    name: 'Michael D.',
    title: 'Investor',
    text: 'Insights from service drove 30% lift in our conversions, this product service is essential for your company growth strategy.',
    x: 400,
    y: 40,
  },
  {
    avatar: imgApi.avatar[3],
    name: 'Kylie Lutz',
    title: 'Freelancer',
    text: 'The company really helped with my personal branding - everything from conception to execution was amazing and super professional. Looking forwards for upgradation.',
    x: 480,
    y: 145,
  },
  {
    avatar: imgApi.avatar[4],
    name: 'Mark Twin',
    title: 'Developer',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 270,
    y: 220,
  },
  {
    avatar: imgApi.avatar[5],
    name: 'Anne',
    title: 'Content Writer & Artist',
    text: 'These folks are my go-to for any design or branding services. Excellent communication and I feel like I`m always a priority for them.',
    x: 150,
    y: 200,
  },
  {
    avatar: imgApi.avatar[6],
    name: 'Bryan S.',
    title: 'Manager',
    text: 'Love your stuff, the quality has been incredible year after year. I tell everyone I know that they have to try the product. Thank you to the team the whole team.',
    x: 100,
    y: 40,
  },
  {
    avatar: imgApi.avatar[7],
    name: 'Kamren Hays',
    title: 'Marketing Head',
    text: 'Product bring 10x multiplier in terms of both ease and spread of use. I`m able to quickly and easily execute on my marketing strategies. That the fundamental difference from other services.',
    x: 330,
    y: 100,
  },
  {
    avatar: imgApi.avatar[8],
    name: 'Diane Smith',
    title: 'Sales Head',
    text: 'Team offers a powerful suite of tools that every client must have. And if you get stuck their support team will help out. Its is fast, reliable and has no complications at all.',
    x: 30,
    y: 50,
  },
  {
    avatar: imgApi.avatar[9],
    name: 'Mikayla Mccullough',
    title: 'Designer',
    text: 'The vibe, level of inquiry, feedback and traffic at our product services and newly designed booth at a recent conference was very positive.',
    x: 400,
    y: 150,
  },
  {
    avatar: imgApi.avatar[10],
    name: 'Anna',
    title: 'Freelance',
    text: 'Greatfully.',
    x: 480,
    y: 100,
  },
  {
    avatar: imgApi.avatar[11],
    name: 'Jona',
    title: 'Freelance',
    text: 'So easy to understand.',
    x: 250,
    y: 100,
  },
  {
    avatar: imgApi.avatar[12],
    name: 'Anson',
    title: 'Freelance',
    text: 'The vibe, level of inquiry, feedback and traffic at our product services and newly designed booth at a recent conference was very positive.',
    x: 150,
    y: 260,
  },
  {
    avatar: imgApi.avatar[13],
    name: 'Silla',
    title: 'Freelance',
    text: 'Team offers a powerful suite of tools that every client must have. And if you get stuck their support team will help out. Its is fast, reliable and has no complications at all.',
    x: 300,
    y: 140,
  },
  {
    avatar: imgApi.avatar[14],
    name: 'Sula',
    title: 'Freelance',
    text: 'The company really helped with my personal branding - everything from conception to execution was amazing and super professional. Looking forwards for upgradation.',
    x: 482,
    y: 250,
  },
  {
    avatar: imgApi.avatar[15],
    name: 'Abdi',
    title: 'Freelance',
    text: 'The company really helped with my personal branding - everything from conception to execution was amazing and super professional. Looking forwards for upgradation.',
    x: 435,
    y: 210,
  },
];

export default testimonialsData;
