import imgApi from '~/public/images/imgAPI';

const testimonialsData = [
  {
    avatar: imgApi.avatar[0],
    name: 'John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 100,
    y: 150,
  },
  {
    avatar: imgApi.avatar[1],
    name: 'John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 120,
    y: 100,
  },
  {
    avatar: imgApi.avatar[2],
    name: 'John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 400,
    y: 40,
  },
  {
    avatar: imgApi.avatar[3],
    name: 'John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 480,
    y: 145,
  },
  {
    avatar: imgApi.avatar[4],
    name: 'John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 270,
    y: 220,
  },
  {
    avatar: imgApi.avatar[5],
    name: 'John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 150,
    y: 200,
  },
  {
    avatar: imgApi.avatar[6],
    name: 'John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 100,
    y: 40,
  },
  {
    avatar: imgApi.avatar[7],
    name: 'John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 330,
    y: 100,
  },
  {
    avatar: imgApi.avatar[8],
    name: 'John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 30,
    y: 50,
  },
  {
    avatar: imgApi.avatar[9],
    name: 'John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 400,
    y: 150,
  },
  {
    avatar: imgApi.avatar[10],
    name: 'John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 480,
    y: 100,
  },
  {
    avatar: imgApi.avatar[11],
    name: 'John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 250,
    y: 100,
  },
  {
    avatar: imgApi.avatar[12],
    name: 'John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 150,
    y: 260,
  },
  {
    avatar: imgApi.avatar[13],
    name: 'John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 300,
    y: 140,
  },
  {
    avatar: imgApi.avatar[14],
    name: 'John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 482,
    y: 250,
  },
  {
    avatar: imgApi.avatar[15],
    name: 'John Doe',
    title: 'Company Dot Com',
    text: 'Vestibulum faucibus eget erat eget pretium. Donec commodo convallis ligula.',
    x: 435,
    y: 210,
  },
];

export default testimonialsData;
